### PR TITLE
More secure defaults

### PR DESCRIPTION
**Pull request by tersmitten**

### CODE REVIEW

**Comment by tersmitten** [comment]
We recently audited this middleware and found that the defaults could (should) be a bit more secure. I hope that you agree with the changes we made.

**Note** that this change is **not backwards compatible**

**Comment by tersmitten** [comment]
Can you collaborate @carc1n0gen ?

**Comment by carc1n0gen** [comment]
My bad. That was supposed to be a thumb up

**Comment by bryanjhv** [comment]
I'd love to see which certified tests on security did you realize to this package, because in that PR I just see code style changes (which, if you read past issues, I don't plan on changing), adding a lot of stuff to an useless file for the working of this (.gitignore), and changing some booleans that are **not** safe to change because **not** everyone on the PHP world uses **HTTPS** yet. If you come here and show me, reasonably (with statistics), that your "defaults" are good for most people, I promise I'll take this into account. Otherwise, I recommend reading about cookies in PHP, session handling and the related topics.
Thanks in advance!

**Comment by tersmitten** [comment]
Thanks for the negativity, that was really necessary.

**Comment by tersmitten** [comment]
We just prefer it to be more secure by default, that's all

**Comment by bryanjhv** [comment]
Sorry for hurting your feelings, but I didn't feel like reviewing.

I'll list the reasons here:
1. It's best to open an issue first.
2. Useful changes only accepted.
3. Make sure your way is the best.
4. Read PHP docs, they complete you.

I explain (3) and (4) with an example:
```php
<?php

// Bad, assumes HTTPS
$defaults = ['secure' => true];

// Good, as of PHP docs
// But needs fixes, for IIS (sets "off" too)
$defaults = ['secure' => !empty($_SERVER['HTTPS'])];
```

Anyway, thanks for contributing! I hope you get to know the language a bit more.

**Pull request closed without merging**
